name: retrofit_generator
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: rafal.wachol <email@example.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  analyzer: ^0.32.1
  analyzer_plugin: '0.0.1-alpha.4'
  code_builder: "^3.1.2"
  build: ^0.12.0
  build_config: ^0.3.1
  source_gen: ^0.9.0
  built_collection: '>=2.0.0 <4.0.0'
  built_value: ^5.5.5

dev_dependencies:
  build_runner: ^0.9.0
  build_test: ^0.10.0
  test: ^1.0.0
